import { Ball } from './ball';
import { MegaBall } from './mega-ball';

/** Type used to convert Python model to TypeScript Type */
export type WinningSetPython = {
	date: string;
	first_ball: Ball;
	second_ball: Ball;
	third_ball: Ball;
	fourth_ball: Ball;
	fifth_ball: Ball;
	mega_ball: MegaBall;
	megaplier: number;
	jackpot_winners: number;
	five_match_winners: number;
	four_match_w_mega_winners: number;
	four_match_winners: number;
	three_match_w_mega_winners: number;
	three_match_winners: number;
	two_match_w_mega_winners: number;
	one_match_w_mega_winners: number;
	mega_match_winners: number;
	estimated_jackpot: number;
	cash_option: number;
	five_match_prize: number;
	four_match_w_mega_prize: number;
	four_match_prize: number;
	three_match_w_mega_prize: number;
	three_match_prize: number;
	two_match_w_mega_prize: number;
	one_match_w_mega_prize: number;
	mega_match_prize: number;
	jackpot_megaplier_winner: number;
	five_match_megaplier_winners: number;
	four_match_w_mega_megaplier_winners: number;
	four_match_megaplier_winners: number;
	three_match_w_mega_megaplier_winners: number;
	three_match_megaplier_winners: number;
	two_match_w_mega_megaplier_winners: number;
	one_match_w_mega_megaplier_winners: number;
	mega_match_megaplier_winners: number;
	five_match_megaplier_prize: number;
	four_match_w_mega_megaplier_prize: number;
	four_match_megaplier_prize: number;
	three_match_w_mega_megaplier_prize: number;
	three_match_megaplier_prize: number;
	two_match_w_mega_megaplier_prize: number;
	one_match_w_mega_megaplier_prize: number;
	mega_match_megaplier_prize: number;
};
